import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SRC_ROOT = path.resolve(__dirname, '..');
const CSV_PATH = path.resolve(SRC_ROOT, 'assets', 'textMap.csv');
const OUTPUT_PATH = path.resolve(SRC_ROOT, 'utils', 'i18n.ts');

const LANGUAGE_KEYS = ['chs', 'cht', 'en-us', 'en-uk', 'jpn'];

const fail = (message) => {
  console.error(`[buildTextMap] ${message}`);
  process.exitCode = 1;
  throw new Error(message);
};

const parseCsv = (content) => {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;

  const pushField = () => {
    row.push(field);
    field = '';
  };

  const pushRow = () => {
    // drop trailing completely empty rows
    if (row.length === 1 && row[0] === '') {
      row = [];
      return;
    }
    rows.push(row);
    row = [];
  };

  for (let index = 0; index < content.length; index += 1) {
    const char = content[index];

    if (inQuotes) {
      if (char === '"') {
        const next = content[index + 1];
        if (next === '"') {
          field += '"';
          index += 1;
        } else {
          inQuotes = false;
        }
      } else {
        field += char;
      }
      continue;
    }

    if (char === '"') {
      inQuotes = true;
      continue;
    }
    if (char === ',') {
      pushField();
      continue;
    }
    if (char === '\n') {
      pushField();
      pushRow();
      continue;
    }
    if (char === '\r') {
      continue;
    }

    field += char;
  }

  pushField();
  pushRow();

  return rows;
};

const sanitizeHeader = (value) => value.replace(/^\uFEFF/, '').trim();

const toHumanTimestamp = (date) => {
  const pad = (value) => String(value).padStart(2, '0');
  return (
    `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ` +
    `${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`
  );
};

const escapeTsString = (value) => JSON.stringify(value ?? '');

const readTextMapCsv = async () => {
  const raw = await fs.readFile(CSV_PATH, 'utf8');
  const rows = parseCsv(raw);
  if (!rows.length) {
    fail(`CSV is empty: ${CSV_PATH}`);
  }

  const header = rows[0].map((cell) => sanitizeHeader(cell));
  const expected = ['key', ...LANGUAGE_KEYS];
  const keyIndex = header.indexOf('key');
  if (keyIndex < 0) {
    fail(`Invalid CSV header. Missing "key" column. Got: ${header.join(',')}`);
  }
  const sliced = header.slice(keyIndex, keyIndex + expected.length);
  if (sliced.length < expected.length || expected.some((key, index) => sliced[index] !== key)) {
    fail(
      `Invalid CSV header. Expected: ${expected.join(',')} after "key". Got: ${header.join(',')}`
    );
  }

  /** @type {Map<string, Record<string, string>>} */
  const map = new Map();
  for (const row of rows.slice(1)) {
    if (!row.length) continue;
    const key = (row[keyIndex] ?? '').trim();
    if (!key || key.startsWith('#')) continue;

    if (map.has(key)) {
      fail(`Duplicate text key: ${key}`);
    }

    /** @type {Record<string, string>} */
    const entry = {};
    for (let index = 0; index < LANGUAGE_KEYS.length; index += 1) {
      const language = LANGUAGE_KEYS[index];
      entry[language] = (row[keyIndex + 1 + index] ?? '').replace(/\r/g, '');
    }

    if (LANGUAGE_KEYS.every((language) => !entry[language].trim())) {
      fail(`Text key has no translations (all empty): ${key}`);
    }

    map.set(key, entry);
  }

  return map;
};

const ensureAtLeastOneLanguageComplete = (map) => {
  const keys = Array.from(map.keys());
  if (!keys.length) return;

  const completions = LANGUAGE_KEYS.map((language) => {
    const missing = keys.filter((key) => !(map.get(key)?.[language] ?? '').trim());
    return { language, missing };
  });

  const complete = completions.find((item) => item.missing.length === 0);
  if (!complete) {
    const summary = completions
      .map((item) => `${item.language}:${item.missing.length} missing`)
      .join(', ');
    fail(`No language is complete. (${summary})`);
  }
};

const generateI18nTs = (map) => {
  const now = new Date();
  const keys = Array.from(map.keys()).sort((a, b) => a.localeCompare(b, 'en'));

  const lines = [];
  lines.push('// THIS FILE IS AUTO-GENERATED by `npm run build:TextMap`. DO NOT EDIT MANUALLY!');
  lines.push('// 此文件由 `npm run build:TextMap` 自动生成，请勿手动修改！');
  lines.push(`// Comment in https://docs.google.com/spreadsheets/d/1Ed6lFZ9gCsbkMXFpX-UNnFm70zo4deoUghjqLibRudU/edit?usp=sharing to suggest changes.`);
  lines.push(`// Textmap generated at: ${toHumanTimestamp(now)} (UTC+8)`);
  lines.push('');
  lines.push("export type UiLanguage = 'chs' | 'cht' | 'en-us' | 'en-uk' | 'jpn';");
  lines.push('');
  lines.push('export const UI_LANGUAGE_OPTIONS = [');
  lines.push("  { value: 'chs', labelKey: 'common.uiLanguage.chs' },");
  lines.push("  { value: 'cht', labelKey: 'common.uiLanguage.cht' },");
  lines.push("  { value: 'en-us', labelKey: 'common.uiLanguage.enUs' },");
  lines.push("  { value: 'en-uk', labelKey: 'common.uiLanguage.enUk' },");
  lines.push("  { value: 'jpn', labelKey: 'common.uiLanguage.jpn' },");
  lines.push('] as const;');
  lines.push('');
  lines.push('export const getDefaultSecondaryLanguage = (primary: UiLanguage): UiLanguage =>');
  lines.push("  primary === 'en-us' || primary === 'en-uk' ? 'chs' : 'en-us';");
  lines.push('');
  lines.push('export const isUiLanguage = (value: unknown): value is UiLanguage =>');
  lines.push(
    "  value === 'chs' || value === 'cht' || value === 'en-us' || value === 'en-uk' || value === 'jpn';"
  );
  lines.push('');
  lines.push('export const detectDefaultUiLanguage = (): UiLanguage => {');
  lines.push("  if (typeof navigator === 'undefined') return 'en-us';");
  lines.push("  const candidates = Array.isArray(navigator.languages) ? navigator.languages : [];");
  lines.push("  const fallback = navigator.language ? [navigator.language] : [];");
  lines.push('  const languages = [...candidates, ...fallback].filter(Boolean);');
  lines.push('  for (const raw of languages) {');
  lines.push('    const language = String(raw).toLowerCase();');
  lines.push("    if (language.startsWith('zh')) {");
  lines.push("      if (language.includes('hant') || language.includes('tw') || language.includes('hk') || language.includes('mo')) {");
  lines.push("        return 'cht';");
  lines.push('      }');
  lines.push("      return 'chs';");
  lines.push('    }');
  lines.push("    if (language.startsWith('ja')) return 'jpn';");
  lines.push("    if (language.startsWith('en')) {");
  lines.push("      if (language.includes('gb') || language.includes('uk')) return 'en-uk';");
  lines.push("      return 'en-us';");
  lines.push('    }');
  lines.push('  }');
  lines.push("  return 'en-us';");
  lines.push('};');
  lines.push('');
  lines.push("type TextMapEntry = { chs?: string; cht?: string; 'en-us'?: string; 'en-uk'?: string; jpn?: string };");
  lines.push('');
  lines.push('export const TEXT_MAP: Record<string, TextMapEntry> = {');
  for (const key of keys) {
    const entry = map.get(key);
    const record = {};
    for (const language of LANGUAGE_KEYS) {
      const value = entry?.[language] ?? '';
      if (value.trim()) {
        record[language] = value;
      }
    }
    lines.push(`  ${escapeTsString(key)}: ${JSON.stringify(record)},`);
  }
  lines.push('};');
  lines.push('');
  lines.push('export type TextKey = string;');
  lines.push('');
  lines.push('type ReplaceParams = Record<string, string | number>;');
  lines.push('');
  lines.push('const replaceParams = (value: string, params?: ReplaceParams): string => {');
  lines.push('  if (!params) return value;');
  lines.push('  return value.replace(/\\{(\\w+)\\}/g, (match, name) => {');
  lines.push('    const replacement = params[name];');
  lines.push('    return replacement === undefined ? match : String(replacement);');
  lines.push('  });');
  lines.push('};');
  lines.push('');
  lines.push('export const t = (');
  lines.push('  key: TextKey,');
  lines.push('  primary: UiLanguage,');
  lines.push('  secondary: UiLanguage,');
  lines.push('  params?: ReplaceParams,');
  lines.push('): string => {');
  lines.push('  const entry = TEXT_MAP[key];');
  lines.push('  if (!entry) return "";');
  lines.push('  const primaryRaw = entry[primary] ?? "";');
  lines.push('  const secondaryRaw = entry[secondary] ?? "";');
  lines.push('  const primaryTrimmed = primaryRaw.trim();');
  lines.push('  const secondaryTrimmed = secondaryRaw.trim();');
  lines.push('  const resolved = primaryTrimmed ? primaryRaw : secondaryTrimmed ? secondaryRaw : "";');
  lines.push('  return resolved ? replaceParams(resolved, params) : "";');
  lines.push('};');
  lines.push('');

  return lines.join('\n') + '\n';
};

const main = async () => {
  const map = await readTextMapCsv();
  ensureAtLeastOneLanguageComplete(map);

  await fs.mkdir(path.dirname(OUTPUT_PATH), { recursive: true });
  const ts = generateI18nTs(map);
  await fs.writeFile(OUTPUT_PATH, ts, 'utf8');

  console.log(`[buildTextMap] Wrote ${OUTPUT_PATH} (${map.size} keys)`);
};

main().catch((error) => {
  if (process.exitCode) return;
  console.error(error);
  process.exit(1);
});
